### ISSUE TITLE
Populate code samples with docstrings

### ISSUE THREAD

**Issue by olegbbtr** [PacktPublishing/Practical-Deep-Reinforcement-Learning#2]
It is generally a good thing to provide docstrings for any functions with a description of input parameters and returned value

**Comment by techsachinkumar** [comment]
Due to pre-publication book title change, repo was migrated here: [Deep Reinforcement Learning Hands-On](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On).

Please use the new repo for issues and contributions. This repo is frozen.

Closed.
