### ISSUE TITLE
ch13 requires golang for installation

### ISSUE THREAD

**Issue by olegbbtr** [PacktPublishing/Practical-Deep-Reinforcement-Learning#6]
To build package `go-vncdriver` golang is required. This should be mentioned in the book.

**Comment by techsachinkumar** [comment]
Due to pre-publication book title change, repo was migrated here: [Deep Reinforcement Learning Hands-On](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On).

Please use the new repo for issues and contributions. This repo is frozen.

Closed.
