### ISSUE TITLE
Prebuilt docker image for ch13 

### ISSUE THREAD

**Issue by olegbbtr** [PacktPublishing/Practical-Deep-Reinforcement-Learning#9]
Patched version of WoB's docker image should be uploaded to http://dockerhub.com/ and the new image name should be put into the book and to `ch13/adhoc/start_docker.sh`

In this case, `ch13/wob_fixes` shouldn't be mentioned in the book, and some disclaimer should be added to it's README, explaining that those actions now don't need to be performed.

**Comment by Shmuma** [comment]
Pushed in shmuma/miniwob repo: https://hub.docker.com/r/shmuma/miniwob/
Updated adhoc scripts, but still need to update the text.

Let's keep wob_fixes dir for future refereneces and for somebody interested in miniwob internals.
